### ISSUE TITLE
documentation TODO

### ISSUE THREAD

**Issue by keggsmurph21** [jonorthwash/ud-annotatrix#320]
- [ ] top-level README
  - [ ] about, link to [universal dependencies](https://universaldependencies.org), motivation, links to live versions, supported formats
  - [ ] features list by setup type (with/without server)
  - [ ] installation instructions, prerequisites
  - [ ] development/contribution instructions
  - [ ] keyboard shortcuts, how-to manual for features
- [ ] in-app help modal
- [ ] inline comments => API docs

**Comment by keggsmurph21** [comment]
- [ ] tag a release version

**Comment by keggsmurph21** [comment]
@jonorthwash , check out b0e189c and let me know what you think (per our conversation the other day). some stuff still needs to be filled in obviously, but the general structure is mostly done i think

**Comment by keggsmurph21** [comment]
- [ ] set up a real version at [`http://annotator.murp.us/`](http://annotator.murp.us)

**Comment by keggsmurph21** [comment]
- [ ] fill in the `how to use` columns in the README
 - [ ] create an API Documentation file at `documentation/README.md`
