### ISSUE TITLE
Current roadmap

### ISSUE THREAD

**Issue by yaskevich** [jonorthwash/ud-annotatrix#357]
- [ ] 1. git integration (needs clarification) #376
  - [ ] add fork from GitHub url button to the /annotatrix page
  - [ ] add fork from GitHub url textbox to the / page
  - [ ] support for different url schemes (e.g. raw.githubusercontent.com, github.com, etc.)
  - [ ] button to submit a pull request
  - [ ] show diffs before finalizing the PR
- [ ] 2. better autocomplete #373
- [ ] 3. support for long sentences (zooming/layout) #175  (+ #143 #161)
- [ ] 4. keyboard support, undo/redo, #171 (and #135) 
- [ ] 5. disambiguation interface, textbox editing #10
- [ ] 6. support for enhanced dependencies #178
- [ ] 7. fixing code regressions, refactoring, UI
  - [x] app in static mode has to store data in LocalStorage #339
  - [x] app in static mode should not emit messages to a server #353
  - [ ] ....

**Comment by jonorthwash** [comment]
Could you link the ones with issues to those issues?  You can e.g., just add "(#339)" at the end of the LocalStorage line.

**Comment by yaskevich** [comment]
I've created new issues on topics mentioned above or left a comment about renewing issue if it existed, so this meta-issue is no longer needed.

**Comment by jonorthwash** [comment]
Could you edit the original comment and add links to the issues you created?  E.g., "- [ ] better autocomplete → #373".  Then I'll close this issue.

**Comment by yaskevich** [comment]
Crosslinked.

**Comment by jonorthwash** [comment]
> 3. support for long sentences (zooming/layout) #143

While #143 is relevant, #175 is the main issue.  I guess #161 is also relevant.

**Comment by jonorthwash** [comment]
> 4. keyboard support, undo/redo, #135

That is relevant, but #171 is the main issue.

**Comment by jonorthwash** [comment]
> 5. disambiguation interface, textbox editing

#10

**Comment by jonorthwash** [comment]
Please add the issues to the main list.

**Comment by yaskevich** [comment]
Thanks for the links, updated.
